### ISSUE TITLE
.env file missing in prisma folder... should be local folder

### ISSUE THREAD

**Issue by Xaedblade** [Errorname/prisma-multi-tenant#30]
I am getting the below error when installing the new alpha25 version. It looks like it desires the .env file to be in a prisma folder, but my folder is called tenant. As I have a folder for multitenant use and a folder for shared database.

Unknown Error!
Error: Couldn't find the prisma/.env file
    at /Users/username/Development/project/backend/src/prisma/tenant/node_modules/prisma-multi-tenant/build/shared/env.js:21:15
    at Generator.next (<anonymous>)
    at fulfilled (/Users/username/Development/project/backend/src/prisma/tenant/node_modules/prisma-multi-tenant/build/shared/env.js:5:58)

**Comment by Errorname** [comment]
Thanks for raising this issue 🙏 

Can you share you folder structure? Where does your `schema.prisma` & `.env` files are located?

**Comment by Xaedblade** [comment]
so the folder structure is as below:
prisma
|-shared
|-tenants
   |- schema.prisma
   |- .env


so the tenants folder is where I use multi tenant prisma as this is a shared structure. and the shared folder is for users and system settings

**Comment by Xaedblade** [comment]
so the folder structure is as below:

src->prisma->tenants-> the .env file and schema.prisma file are here

so the tenants folder is where I use multi tenant prisma as this is a shared structure. and the shared folder is for users and system settings

**Comment by Errorname** [comment]
I see. Do you have different schema.prisma files between `tenants/` and `shared/` ?

**Comment by Xaedblade** [comment]
yes, I only have the tenants folder using the multi tenant prisma. the other is just vanilla prisma

**Comment by Errorname** [comment]
Okay, how is your schema.prisma different between those two folders ?

**Comment by Xaedblade** [comment]
the Tenants have tenant data which is needed to create the individual databases for each tenant
the Shared is for site specific data that is shared across all tenants

**Comment by Xaedblade** [comment]
so I want the tenants to be the only prisma multi tenant. I feel that it should just reside there. It worked on the older versions, but not with the new one

**Comment by Errorname** [comment]
Ah okay, I see. So because you have a different architecture, the current installation command isn't working. The current installation command tries to edit the `prisma/.env` file to add the required env variables.

I'll try to fix that, but in the meantime, you can adapt your code and slightly modify your folder structure:
```
- prisma
  - tenants
    - prisma
      - .env
      - schema.prisma
  - shared
    - ...
```

This way, `prisma-multi-tenant` should be able to find the `.env` file in the correct place.

Is this workaround working for you ?

**Comment by Xaedblade** [comment]
Ok I'll give this a try thanks!

**Comment by Xaedblade** [comment]
No I'm still getting the same error

**Comment by Errorname** [comment]
From which directory do you run the cli ?

**Comment by Xaedblade** [comment]
I've run the cli from tenants and tenants->prisma.
it still trying to pull from the base directory

**Comment by Errorname** [comment]
Unfortunately, I cannot reproduce. Can you create a small reproduction repository so that I can take a look?

**Comment by Xaedblade** [comment]
you can view an example here: https://github.com/Xaedblade/prisma-multi-tenant-example

**Comment by Errorname** [comment]
Hi @Xaedblade, I finally found some time to work on `prisma-multi-tenant` to fix some bugs. However, your reproduction repository does not seem to be accessible anymore. Can you make it available ?

**Comment by Xaedblade** [comment]
Sorry it is active again for you

**Comment by Errorname** [comment]
Hi @Xaedblade, I think I found why it isn't working:

In order for `prisma-multi-tenant@2.0.0-beta.2` to work, you need to have a `prisma/` folder with both a `schema.prisma` file and a `.env` file in it. (So for you, you'll need to move `src/prisma/tenant/schema.prisma` to `src/prisma/tenant/prisma/schema.prisma` and create a  `src/prisma/tenant/prisma/.env` file)

Also, make sure you have the correct prisma version (See compatibility here: [releases](https://github.com/Errorname/prisma-multi-tenant/releases))

Let me know if you were able to fix the issue

**Comment by Errorname** [comment]
Since there have been no activity on this issue for a while, I'll close it. Don't hesitate to re-open it if  needed
