### ISSUE TITLE
Cannot find module 'find-up'

### ISSUE THREAD

**Issue by solinad21** [Errorname/prisma-multi-tenant#69]
i can not run ok prisma-multi-tenant, 

after installing it when run prisma-multi-tenant init, i get errors:

`prisma-multi-tenant init
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'find-up'
Require stack:
- C:\Users\apolo13\AppData\Roaming\npm\node_modules\prisma-multi-tenant\node_modules\@prisma-multi-tenant\shared\build\shell.js
- C:\Users\apolo13\AppData\Roaming\npm\node_modules\prisma-multi-tenant\node_modules\@prisma-multi-tenant\shared\build\env.js
- C:\Users\apolo13\AppData\Roaming\npm\node_modules\prisma-multi-tenant\node_modules\@prisma-multi-tenant\shared\build\index.js
- C:\Users\apolo13\AppData\Roaming\npm\node_modules\prisma-multi-tenant\build\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\apolo13\AppData\Roaming\npm\node_modules\prisma-multi-tenant\node_modules\@prisma-multi-tenant\shared\build\shell.js:16:35)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\apolo13\\AppData\\Roaming\\npm\\node_modules\\prisma-multi-tenant\\node_modules\\@prisma-multi-tenant\\shared\\build\\shell.js',
    'C:\\Users\\apolo13\\AppData\\Roaming\\npm\\node_modules\\prisma-multi-tenant\\node_modules\\@prisma-multi-tenant\\shared\\build\\env.js',
    'C:\\Users\\apolo13\\AppData\\Roaming\\npm\\node_modules\\prisma-multi-tenant\\node_modules\\@prisma-multi-tenant\\shared\\build\\index.js',
    'C:\\Users\\apolo13\\AppData\\Roaming\\npm\\node_modules\\prisma-multi-tenant\\build\\index.js'
  ]
}`

**Comment by BjoernRave** [comment]
yea, I got the same error

**Comment by Errorname** [comment]
Hi everyone! This bug has been fixed with the release of pmt@2.4.1. Thanks for your patience 🙏
