### ISSUE TITLE
Comptability issues with latest prisma 2.12.0

### ISSUE THREAD

**Issue by asaadawey** [Errorname/prisma-multi-tenant#74]
Updating prisma to v2.12 and nexus leads me to this error

```
Error: Unknown property debug provided to PrismaClient constructor.
Read more at https://pris.ly/d/client-constructor
    at validatePrismaClientOptions (/home/ahmed/Desktop/CarRental-Backend/node_modules/.prisma-multi-tenant/management/runtime/index.js:78546:13)
    at new NewPrismaClient (/home/ahmed/Desktop/CarRental-Backend/node_modules/.prisma-multi-tenant/management/runtime/index.js:78611:9)
    at Management.<anonymous> (/home/ahmed/Desktop/CarRental-Backend/node_modules/@prisma-multi-tenant/shared/build/management.js:39:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ahmed/Desktop/CarRental-Backend/node_modules/@prisma-multi-tenant/shared/build/management.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mvhysko** [comment]
Hi @asaadawey . I have the same error. Did you manage to find a solution?

**Comment by asaadawey** [comment]
@mvhysko 
Yes 
I have edited the node_modules folder temporarily 
I removed the method that verifies prisma client constructor

**Comment by jimsimon** [comment]
Any chance this can be merged in and released?

**Comment by Intelligix** [comment]
Any chance this can be merged in and released?

**Comment by mvhysko** [comment]
@jimsimon @Intelligix Sorry guys. This PR is not valid. Current version of this lib should be adapted to the new Prisma version. I do not have a time to do it.

**Comment by totaland** [comment]
Is that just mean changing the version in package.json to be using the new Prisma right? 
@mvhysko I can do that and make the pull request

**Comment by totaland** [comment]
@mvhysko https://github.com/Errorname/prisma-multi-tenant/pull/79
Could you help with fixing the test for this PR please champ?
